import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Specorator Builder — if you want to view the source, visit the plugin's repository.
*/`;

const prod = process.argv[2] === "production";

// GrapesJS ships its core UI styles as a stylesheet. The preset/basic-blocks
// plugins inject their own styles at runtime, so we only need the core CSS here.
// We concatenate it with the plugin's own styles into Obsidian's styles.css.
function buildStyles() {
  const grapes = readFileSync(
    "node_modules/grapesjs/dist/css/grapes.min.css",
    "utf8"
  );
  const own = readFileSync("src/styles/specorator.css", "utf8");
  writeFileSync(
    "styles.css",
    `/* Bundled GrapesJS core styles */\n${grapes}\n\n/* Specorator Builder styles */\n${own}\n`
  );
}

const stylesPlugin = {
  name: "specorator-styles",
  setup(build) {
    build.onStart(buildStyles);
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [stylesPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
